# .github/workflows/compress_epg.yml

name: Compress EPG XML

on:
  workflow_dispatch:  # Manuel tetikleme
  
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Compress epg.xml to epg.xml.gz
        run: |
          python deneme.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add epg.xml.gz
          git commit -m "Add compressed epg.xml.gz"
          git push

      - name: Upload artifact (Opsiyonel)
        uses: actions/upload-artifact@v4
        with:
          name: epg.xml.gz
          path: epg.xml.gz
