name: Scrape Vavoo Channels

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları yükle
        run: |
          pip install requests beautifulsoup4

      - name: Scraper'ı çalıştır
        run: python deneme.py

      - name: Git ayarları
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Değişiklikleri commit et ve pushla
        run: |
          git add v/data.txt
          git diff --cached --quiet || git commit -m "Auto update: data.txt via scraper"
          git push
