name: Scrape Vavoo Channels

on:
  workflow_dispatch:  # Manuel çalıştırma için

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Python scraper'ı çalıştır
        run: python deneme.py
