name: Extract m3u8 Links

on:
  workflow_dispatch: # Bu, manuel tetikleme özelliğini etkinleştirir.

jobs:
  extract_m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests beautifulsoup4 
        python -m playwright install

    - name: Run the Python script
      run: |
        python deneme.py  # Burayı script'inizin adıyla değiştirin
