name: Build M3U Playlist

on:
  workflow_dispatch:
  
jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları yükle
        run: |
          pip install --upgrade pip

      - name: M3U oluşturma script'ini çalıştır
        run: python deneme2.py  # script'in adını ve yolunu doğru gir

      - name: Git ayarları ve push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add v/vavoo.m3u
          git diff --cached --quiet || git commit -m "Auto update: vavoo.m3u via GitHub Actions"
          git push
