name: zzzScrzzzipts from Private Repo (D- JSON)

on:
  workflow_dispatch:  # Manuel tetikleme de mümkün

jobs:
  extract-schedule-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 
          
      - name: Run extraction script
        run: python deneme2.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add -A
          git status
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update schedule data [skip ci]" && git push origin main)
