name: Unified Python Workflow

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  run-all-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (veriler)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python dependencies from private repo
        run: |
          pip install -r private_py/requirements.txt

      # ---------------- V Section ----------------
      - name: Run datatxt.py
        run: python private_py/vavoo/datatxt.py

      - name: Run datatxtm3u.py
        run: python private_py/vavoo/datatxtm3u.py

#     - name: Run dizi_gunluk.py
#       run: python private_py/vavoo/dizi_gunluk.py

#     - name: Run diziler_m3u.py
#       run: python private_py/vavoo/diziler_m3u.py

      - name: Run sporekrani.py
        run: python private_py/vavoo/sporekrani.py

      - name: Run spor_ekrani_m3u.py
        run: python private_py/vavoo/spor_ekrani_m3u.py

      # ---------------- D Section ----------------
      - name: Run schedule_aljson.py
        run: python private_py/daddyliveevent/schedule_aljson.py

      - name: Run server_key_schedule.py
        run: python private_py/daddyliveevent/server_key_schedule.py

      - name: Run schedule_son.py
        run: python private_py/daddyliveevent/schedule_son.py

      - name: Run eventm3u.py
        run: python private_py/daddyliveevent/eventm3u.py

      - name: Run convertm3u.py
        run: python private_py/daddyliveevent/convertm3u.py

      # ---------------- S Section ----------------
      - name: Run ana_domain.py
        run: python private_py/selcuk/ana_domain.py

      - name: Run baseurl.py
        run: python private_py/selcuk/baseurl.py

#     - name: Run datahtml.py
#       run: python private_py/selcuk/datahtml.py

#     - name: Run mac_verileri.py
#       run: python private_py/selcuk/mac_verileri.py

      - name: Run encode.py
        run: python private_py/selcuk/encode.py

      - name: Run m3u.py
        run: python private_py/selcuk/m3u.py

      # ---------------- Commit / Push ----------------
      - name: Add all changes
        run: git add -A

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update all output files via unified workflow" || echo "No changes to commit"
          git push origin main
