name: Run Python Scripts from Private Repo ( D )

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */1 * * *'

concurrency:
  group: golvar-d
  cancel-in-progress: true

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (veriler)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies from private repo
        run: pip install -r private_py/requirements.txt

      - name: Set Counter String (Using a, b, c)
        id: counter
        run: |
          COUNTER_FILE=d/counter.txt
          if [ ! -f "$COUNTER_FILE" ]; then echo "a" > $COUNTER_FILE; fi
          COUNT=$(cat $COUNTER_FILE)
          echo "Current counter value is $COUNT"
          
          # Change counter value based on logic
          if [ "$COUNT" == "a" ]; then
            echo "b" > $COUNTER_FILE
          elif [ "$COUNT" == "b" ]; then
            echo "c" > $COUNTER_FILE
          elif [ "$COUNT" == "c" ]; then
            echo "a" > $COUNTER_FILE  # Reset to 'a' after 'c'
          fi

          echo "::set-output name=count::$COUNT"

      - name: Debugging Counter String Value
        run: |
          echo "Debug: Current counter string value is ${{ steps.counter.outputs.count }}"

      - name: Install Playwright (When Counter is b)
        if: ${{ steps.counter.outputs.count == 'b' }}
        run: pip playwright install

      - name: Run livejson.py (When Counter is b)
        if: ${{ steps.counter.outputs.count == 'b' }}
        run: python d/livejson.py

      - name: Run schedule_aljson.py
        run: python private_py/daddyliveevent/schedule_aljson.py

      - name: Run server_key_schedule.py
        run: python private_py/daddyliveevent/server_key_schedule.py

      - name: Run schedule_son.py
        run: python private_py/daddyliveevent/schedule_son.py

      - name: Run eventm3u.py
        run: python private_py/daddyliveevent/eventm3u.py

      - name: Run convertm3u.py
        run: python private_py/daddyliveevent/convertm3u.py

      - name: Add all changes
        run: git add -A

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update output and counter via workflow D" || echo "No changes to commit"
          git push origin main
