name: Delete Files After Push (Manual or Workflow Trigger)

on:
  workflow_dispatch:  # Manuel tetikleme
  workflow_run:
    workflows: ["Push"]  # Burada "Push Workflow Name" yerine hedef workflow'un adını yazmalısın
    types:
      - completed

jobs:
  delete-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Wait for 45 seconds before proceeding
        run: |
          echo "Waiting for 45 seconds before starting..."
          sleep 45  # 45 saniye bekle

      - name: Delete files, excluding specified ones
        run: |
          echo "Deleting files, keeping exclusions..."

          # Silinmemesi gereken dosyalar
          protected_files=(
            "v/data.html"
            "d/livejson.py"
            "d/logo.txt"
            "d/schedule.json"
            "g/ana_link.txt"
            "g/logo.txt"
            "s/ana_link.txt"
            "s/logo.txt"
            "playlist.m3u"
          )

          # Tüm dosyaları sil
          for file in $(find . -type f); do
            # Dosya silinmesi gerekenlerden mi?
            if [[ ! " ${protected_files[@]} " =~ " ${file} " ]]; then
              echo "Deleting $file"
              rm -f "$file"  # Silme işlemi
            else
              echo "Skipping $file"
            fi
          done

      - name: Commit and Push Cleanup Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Cleanup files after push or manual trigger [auto]" || echo "No changes to commit"
          git push origin main
