name: Delete Files After Push (Manual or Workflow Trigger)

on:
  push:
    paths:
      - sil.txt  # Sadece sil.txt dosyası değiştiğinde çalışacak
  workflow_dispatch:  # Manuel olarak da tetiklenebilir

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure all files are writable (chmod +w)
      run: |
        echo "Ensuring all files are writable"
        chmod -R +w ./v

    - name: Delete all files except data.html in 'v' directory
      run: |
        echo "Deleting files in 'v' directory except data.html"
        for file in ./v/*; do
          if [ "$file" != "./v/data.html" ]; then
            echo "Deleting $file"
            rm -f "$file"
          fi
        done
