name: Delete Files After Push (Manual or Workflow Trigger)

on:
  push:
    paths:
      - sil.txt  # Sadece sil.txt dosyası değiştiğinde çalışacak
  workflow_dispatch:  # Manuel olarak da tetiklenebilir

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete files in 'v' directory except data.html
      run: |
        # v klasöründeki her dosyayı tek tek kontrol et ve data.html dışında sil
        echo "Starting file deletion in './v' directory"
        cd ./v
        for file in *; do
          if [ "$file" != "data.html" ]; then
            echo "Deleting $file"
            rm -f "$file"
          fi
        done
