name: Delete Files Except data.html

on:
  push:
    paths:
      - 'sil.txt'  # Bu dosya eklendiğinde workflow tetiklenecek
  workflow_dispatch:  # Bu tetikleyici manuel çalıştırmaya izin verir

jobs:
  delete-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.email "your-email@example.com"  # GitHub e-posta adresinizi buraya yazın
          git config --global user.name "Your Name"  # GitHub kullanıcı adınızı buraya yazın

      - name: Delete all files except data.html
        run: |
          # 'v' klasöründeki tüm dosyaları sil, data.html hariç
          find v -type f ! -name 'data.html' -exec git rm {} \;
          git commit -m "Delete all files except data.html"
          git push origin main  # Ya da hangi branşta çalıştırmak istiyorsanız
