name: Delete Files After Push (Manual or Workflow Trigger)

on:
  push:
    paths:
      - sil.txt  # Sadece `sil.txt` dosyası değiştiğinde çalışacak
  workflow_dispatch:  # Manuel olarak da tetiklenebilir

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files in the repository (for debugging)
      run: |
        echo "Listing files in the root directory:"
        ls -alh
        echo "Listing files in the 'v' directory before deletion:"
        ls -alh ./v
        echo "Listing files in the 's' directory before deletion:"
        ls -alh ./s

    - name: Delete all files except data.html in the 'v' directory, ana_link.txt, and logo.txt, and delete sil.txt
      run: |
        echo "Current working directory: $(pwd)"
        echo "Listing files in './v' directory before deletion:"
        ls -alh ./v

        # Mutlak yolu kullanarak dosya silme işlemini yapalım
        for file in $(ls ./v); do
          if [[ "$file" != "data.html" ]]; then
            echo "Deleting file: ./v/$file"
            rm -f "./v/$file"
          fi
        done

        # Aynı işlemi './s' klasörü için de yapalım
        echo "Deleting files in './s' directory except ana_link.txt and logo.txt"
        for file in $(ls ./s); do
          if [[ "$file" != "ana_link.txt" && "$file" != "logo.txt" ]]; then
            echo "Deleting file: ./s/$file"
            rm -f "./s/$file"
          fi
        done

        # Silme işleminden önce 'sil.txt' dosyasını da silelim
        echo "Deleting sil.txt in the root directory"
        rm -f ./sil.txt

    - name: List files after deletion (for debugging)
      run: |
        echo "Listing files in the root directory after deletion:"
        ls -alh
        echo "Listing files in the 'v' directory after deletion:"
        ls -alh ./v
        echo "Listing files in the 's' directory after deletion:"
        ls -alh ./s
