name: Delete Files After Push (Manual or Workflow Trigger)

on:
  push:
    paths:
      - sil.txt  # Sadece sil.txt dosyası değiştiğinde çalışacak
  workflow_dispatch:  # Manuel olarak da tetiklenebilir

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete all files except data.html in 'v' directory
      run: |
        # v klasöründe data.html haricindeki tüm dosyaları sil
        for file in ./v/*; do
          if [ "$file" != "./v/data.html" ]; then
            rm -f "$file"
          fi
        done
