name: Delete Files After Push (Manual or Workflow Trigger)

on:
  push:
    paths:
      - sil.txt  # Sadece `sil.txt` dosyası değiştiğinde çalışacak
  workflow_dispatch:  # Manuel olarak da tetiklenebilir

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete all files except data.html, ana_link.txt, and logo.txt, and delete sil.txt
      run: |
        # .v klasöründeki data.html hariç tüm dosyaları sil
        find . -type f -path './v/*' ! -name 'data.html' -exec rm -f {} \;
        
        # s klasöründeki ana_link.txt ve logo.txt hariç tüm dosyaları sil
        find . -type f -path './s/*' ! -name 'ana_link.txt' ! -name 'logo.txt' -exec rm -f {} \;

        # Ana dizindeki sil.txt dosyasını sil
        rm -f ./sil.txt
