name: Run xPython Scripts from Private Repo (D- JSON)

on:
  schedule:
    - cron: '30 */2 * * *'  # Her 2 saatte bir
  workflow_dispatch:

jobs:
  extract-schedule-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 playwright bs4 lxml
          playwright install

      - name: Run livejson.py from private repo (output to public d/)
        run: python private_py/daddylivekanal/livejson.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add d/schedule.json
          git status
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update schedule.json from livejson.py [skip ci]" && git push origin main)
