name: Token Generator and Push

on:
  workflow_dispatch:  # Manuel olarak da tetiklenebilir

jobs:
  generate_and_push_token:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate Token and Save to token.txt
      run: |
        python generate_and_save_token.py

    - name: Commit and Push token.txt
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add token.txt
        git commit -m "Update token.txt with new token"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions'ı otomatik olarak repository'ye push etmek için kullanılır.
