name: Extract Schedule Data

on:
  workflow_dispatch:  # Manual trigger for running the workflow

jobs:
  extract-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install playwright
          pip install bs4
          pip install lxml
          playwright install

      # Run the extraction script
      - name: Run extraction script
        run: python d/livejson.py

      # Commit and push the changes to GitHub if there are modifications
      - name: Commit and push changes if JSON is modified
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add d/schedule.json
          git status
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update schedule data [skip ci]" && git push)
