name: Copy m3u file from public to private repo

on:
  workflow_dispatch:  # Manuel tetikleme

jobs:
  copy_m3u_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the public repository (sitem3u)
      uses: actions/checkout@v3
      with:
        repository: 'MDuymazz/sitem3u'  # Public repo adı: sitem3u
        token: ${{ secrets.GH_TOKEN }}  # Public repo'ya token gerekmez, ancak işlem için kullanabiliriz

    - name: Set up Git for private repository (Py)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Clone the private repository (Py) and checkout the main branch
      run: |
        # Gizli repo'yu klonlarken token'ı kullanarak kimlik doğrulaması yapıyoruz
        git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git  # Gizli repo URL'si
        cd Py
        git checkout main  # Gizli repo'nun default branch'ına checkout yapıyoruz

    - name: Copy m3u file from sitem3u to Py repo
      run: |
        # Public repo'dan m3u dosyasını alıyoruz ve gizli repo'ya kopyalıyoruz
        cp ../sitem3u/d/event.m3u ./d/event.m3u
        
        # Değişiklikleri git'e ekliyoruz ve commit ediyoruz
        git add d/event.m3u
        git commit -m "Update event.m3u with data from public repo"
        
        # Gizli repo'ya push ediyoruz
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git
