name: Run Python Scripts from Private Repo ( D )

on:
  workflow_dispatch:          # Manuel tetikleme için
  # schedule:
  #   - cron: '15 */1 * * *'   # Her saat başı çalıştırılacak

concurrency:
  group: golvar-d
  cancel-in-progress: true

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (veriler)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install playwright
          pip install bs4
          pip install lxml
          playwright install 
      # liveevent scripts

      - name: Run schedule_aljson.py
        run: python private_py/daddyliveevent/livejson.py
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          # Add both HTML and JSON files
          git add d/schedule.json
          # Ignore screenshot files
          git status
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update schedule data [skip ci]" && git push)
