name: Run Daddylive Extractor

on:
  workflow_dispatch:  # Elle çalıştırma
  # schedule:
  # - cron: '0 12 * * *'  # Her gün saat 12:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install httpx

      - name: Run the script
        run: |
          python deneme.py

      - name: Commit and Push schedule.html
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          
          # Manually modify the file to ensure something changes
          echo "Update made at $(date)" >> schedule.html
          
          git add schedule.html
          git commit -m "Update schedule.html"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
