name: Upload m3u file to private repo

on:
  workflow_dispatch:  # Manuel tetikleme

jobs:
  upload_m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source repository
      uses: actions/checkout@v3
      with:
        repository: 'source_user/source_repo'  # Kaynak repo adı
        token: ${{ secrets.GH_TOKEN }}  # Kaynak repo için token

    - name: Set up Git for private repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Copy m3u file to private repo
      run: |
        # Hedef repo'ya erişmek için hedef repository'i checkout ediyoruz
        git clone https://github.com/MDuymazz/Py.git
        cd Py
        
        # Kaynak repo'dan dosyayı kopyalıyoruz
        cp ../d/dosya.m3u ./d/dosya.m3u
        
        # Değişiklikleri commit edip push ediyoruz
        git add d/dosya.m3u
        git commit -m "Add m3u file from source repo"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git

