name: Daddylive HTML Alıcı

on:
  workflow_dispatch:  # Manuel tetikleme

jobs:
  fetch-html:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install selenium chromedriver-binary-auto

    - name: HTML verisini çek
      run: |
        python deneme.py
