name: Run Python Scripts frxom Private Repo ( G )

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

concurrency:
  group: golvar-main
  cancel-in-progress: true

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (veriler)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies from private repo
        run: |
          pip install -r private_py/requirements.txt

      - name: Run Python Scripts
        run: |
          python private_py/golvar/ana_domain.py
          python private_py/golvar/mac_verileri.py
          python private_py/golvar/link_alma.py
          python private_py/golvar/m3u_link.py
          python private_py/golvar/kod_alma.py
          python private_py/golvar/link_hazırlama.py
          python private_py/golvar/encode.py
          python private_py/golvar/verileri_birlestir.py
          python private_py/golvar/txt_to_m3u.py

      - name: Add all changes
        run: |
          git add -A

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update all output files via workflow G" || echo "No changes to commit"
          git push origin main

      - name: Download G1.yml from secret and write to file
        run: |
          echo "${{ secrets.G1_YML_CONTENT }}" | base64 --decode > .github/workflows/g1.yml
          echo "G1.yml content written to .github/workflows/g1.yml"

      - name: Trigger G1 workflow in sitem3u repo
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: MDuymazz/sitem3u  # Burada sitem3u reposu kullanılıyor
          workflow: .github/workflows/g1.yml
          ref: main
