name: Selenium Python Workflow

on:
  workflow_dispatch:  # Bu iş akışını manuel başlatmak için kullanılır

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium
          sudo apt-get install -y wget
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          sudo apt install unzip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin
          rm chromedriver_linux64.zip

      - name: Run Selenium script
        run: |
          python deneme.py
