name: Push .m3u Files to Private Repo

on:
  schedule:
    - cron: '0 */1 * * *'  # Workflow her saat başı çalışacak
  workflow_dispatch:  # Manuel tetikleme

jobs:
  push-m3u-to-private-repo:
    runs-on: ubuntu-latest

    steps:
      # Ana repo'yu checkout ediyoruz
      - name: Checkout repository (for action)
        uses: actions/checkout@v2

      # .m3u dosyasını kontrol ediyoruz
      - name: Prepare .m3u Files
        run: |
          # .m3u dosyasının yolu
          M3U_FILE_PATH="d/event.m3u"
          
          # .m3u dosyasının varlığını kontrol et
          if [ -f "$M3U_FILE_PATH" ]; then
            echo "Found .m3u file, proceeding with push."
          else
            echo ".m3u file not found, exiting."
            exit 1
          fi

      # .m3u dosyasını GitHub Token ile push etmek
      - name: Push .m3u file to private repository
        run: |
          # GitHub Actions token'ını kullanarak kimlik doğrulaması yapıyoruz
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Repo URL'yi kontrol et ve doğru URL ile bağlantıyı ekle
          REPO_URL=https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git
          
          # Uzak repository bağlantısını ekliyoruz
          git remote add private-repo $REPO_URL

          # .m3u dosyasını ekliyoruz
          git add d/event.m3u  # .m3u dosyasını stage ediyoruz

          # Değişiklikleri commit ediyoruz
          git commit -m "Update .m3u file" || echo "No changes to commit"  # Eğer dosyada değişiklik yoksa commit etme

          # Değişiklikleri Py repo'suna push ediyoruz
          git push private-repo main  # .m3u dosyasını push ediyoruz
