name: Sync m3u Files from Public to Py Repo

on:
  workflow_dispatch:  # Manuel olarak tetiklemek için

jobs:
  sync-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Public repo
      uses: actions/checkout@v2
      with:
        repository: 'MDuymazz/sitem3u'
        token: ${{ secrets.GH_TOKEN }}  # GH_TOKEN kullanıldı
        ref: main  # Public repo'nun ana dalını belirtin

    - name: Checkout Py repo
      uses: actions/checkout@v2
      with:
        repository: 'MDuymazz/Py'
        token: ${{ secrets.GH_TOKEN }}  # GH_TOKEN kullanıldı
        ref: main  # Py repo'nun ana dalını belirtin
        path: Py_repo  # Py repo'su yerel dizin olarak 'Py_repo' olarak checkout edilecek

    - name: Copy m3u files from Public to Py repo
      run: |
        cp -r sitem3u/d/*.m3u Py_repo/d/  # Public repo'dan m3u dosyalarını Py repo'suna kopyala

    - name: Commit and Push changes to Py repo
      run: |
        cd Py_repo
        git config --global user.name "MDuymazz"
        git config --global user.email "youremail@example.com"  # GitHub email adresinizi buraya girin
        git add .
        git commit -m "Sync m3u files from Public repo"
        git push origin main  # Ana dalı belirtin
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # GH_TOKEN kullanıldı
