name: Deneme

on:
 
  workflow_dispatch:

jobs:
  run-all-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python dependencies from private repo
        run: |
          pip install -r private_py/requirements.txt

      # ---------------- V Section ----------------
      - name: Run schedule_aljson.py
        run: python private_py/daddyliveevent/schedule_aljson.py

      - name: Run server_key_schedule.py
        run: python private_py/daddyliveevent/server_key.py

      - name: Add all changes
        run: git add -A

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update all output files via unified workflow" || echo "No changes to commit"
          git push origin main
