name: Ruxxxn Python Scripts from Private Repo (D- KANAL)

on:
  workflow_dispatch:          # Manuel tetikleme için

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (veriler)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Python dependencies from private repo
        run: |
          pip install -r private_py/requirements.txt

      # daddylivekanal scripts
      - name: Run kanal_verileri.py
        run: python private_py/daddylivehd1click/html.py

      # Tüm değişiklikleri sahneye al
      - name: Add all changes
        run: |
          git add -A

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update all output files and via workflow D" || echo "No changes to commit"
          git push origin main
