name: Daddylive HTML Alıcı

on:
  workflow_dispatch:  # Manuel çalıştırma

jobs:
  fetch-html:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gerekli paketleri yükle
      run: |
        pip install selenium webdriver-manager

    - name: HTML içeriğini çek
      run: |
        python deneme.py
