name: Merge M3U Playlists and Push ( g )

on:
  workflow_run:
    workflows: ["Run Python Scripts from Private Repo ( G )"]
    types:
      - completed

  workflow_dispatch:  # Manuel çalıştırma

jobs:
  sync-to-private-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout General Repo (sitem3u)
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout Private Repo (Py) using GH_TOKEN
        uses: actions/checkout@v3
        with:
          repository: MDuymazz/Py
          token: ${{ secrets.GH_TOKEN }}
          path: py  # Klon dizini

      - name: Copy M3U Files from General Repo to Py Repo
        run: |
          mkdir -p py/m3u8
          cp -f g/*.m3u py/m3u8/

      - name: Commit & Push to Py Repo
        working-directory: py
        run: |
          git add .
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Sync M3U files from sitem3u"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git HEAD:main

      - name: Clean Up g Folder Except ana_link.txt
        run: |
          echo "Cleaning up g folder (except ana_link.txt)..."
          find g/ -type f ! -name 'ana_link.txt' -print -exec rm -f {} +
