name: Clean g Folder (Except ana_link.txt)

on:
  workflow_dispatch:  # Manuel çalıştırma

jobs:
  clean-g-folder:
    runs-on: ubuntu-latest

    steps:
      # Genel repoyu checkout et
      - name: Checkout General Repo (sitem3u)
        uses: actions/checkout@v2

      # Git ayarlarını yap
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # g klasöründeki dosyaları sil
      - name: Clean Up g Folder Except ana_link.txt
        run: |
          echo "Silme işlemi başlıyor..."
          for file in g/*; do
            if [ "$(basename "$file")" != "ana_link.txt" ]; then
              echo "Siliniyor: $file"
              rm -f "$file"
            fi
          done

      # Silinen dosyaların commit edilip push edilmesi
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update all output files and via workflow D" || echo "No changes to commit"
          git push origin main
