name: Clean g Folder (Except ana_link.txt)

on:
  workflow_dispatch:  # Manuel çalıştırma

jobs:
  clean-g-folder:
    runs-on: ubuntu-latest

    steps:
      # Genel repoyu checkout et
      - name: Checkout General Repo (sitem3u)
        uses: actions/checkout@v2

      # g klasöründeki dosyaları sil
      - name: Clean Up g Folder Except ana_link.txt
        run: |
          git rm -rf g/*  # g klasöründeki tüm dosyaları siler
          git reset g/ana_link.txt  # ana_link.txt dosyasını silmeyi engeller
          
      # Silme işlemi sonrası commit ve push
      - name: Commit and Push Changes
        run: |
          git commit -m "Clean g folder (remove all files except ana_link.txt)"
          git push origin main
