name: Merge M3U Playlists and Push ( G )

on:
  workflow_run:
    workflows: ["Run Python Scripts from Private Repo ( G )"]
    types:
      - completed

  workflow_dispatch:  # Manuel çalıştırma

jobs:
  # Job 1: M3U Playlists birleştirme ve push etme
  merge-m3u-playlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install requests 

      - name: Merge M3U Playlists
        run: |
          python private_py/birlestir.py  # Python scriptini çalıştırır

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          # Stage the playlist.m3u file for commit
          git add .

          # Check if there are any changes to commit
          git diff --cached --quiet || (git commit -m "Update playlist.m3u and clean up files via GitHub Actions" && git push)

  # 10 saniye bekleme
  wait-before-sync:
    runs-on: ubuntu-latest
    needs: merge-m3u-playlists
    steps:
      - name: Wait for 10 seconds before syncing to private repo
        run: |
          echo "Waiting for 10 seconds before syncing to private repo..."
          sleep 10

  # Job 2: M3U dosyalarını Py repo'suna push etme
  sync-to-private-repo:
    runs-on: ubuntu-latest
    needs: wait-before-sync

    steps:
      - name: Checkout General Repo (sitem3u)
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout Private Repo (Py) using GH_TOKEN
        uses: actions/checkout@v3
        with:
          repository: MDuymazz/Py
          token: ${{ secrets.GH_TOKEN }}
          path: py  # Klon dizini

      - name: Copy M3U Files from General Repo to Py Repo
        run: |
          mkdir -p py/m3u8
          cp -f g/*.m3u py/m3u8/

      - name: Commit & Push to Py Repo
        working-directory: py
        run: |
          git add .
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Sync M3U files from sitem3u"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git HEAD:main

  # 10 saniye bekleme
  wait-before-cleaning:
    runs-on: ubuntu-latest
    needs: sync-to-private-repo
    steps:
      - name: Wait for 10 seconds before cleaning g folder
        run: |
          echo "Waiting for 10 seconds before cleaning g folder..."
          sleep 10

  # Job 3: g klasöründeki dosyaları silme (ana_link.txt hariç)
  clean-g-folder:
    runs-on: ubuntu-latest
    needs: wait-before-cleaning  # Önceki job'un tamamlanmasını bekle

    steps:
      # Genel repoyu tekrar checkout et
      - name: Checkout General Repo (sitem3u)
        uses: actions/checkout@v2

      # g klasöründeki tüm dosyaları sil, ana_link.txt hariç
      - name: Clean Up g Folder Except ana_link.txt
        run: |
          # Silmek istemediğimiz dosya dışında tüm dosyaları sil
          find g/* ! -name 'ana_link.txt' -exec rm -f {} \;

      # Silme işlemi sonrası commit ve push
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Clean g folder (remove all files except ana_link.txt)"
          git push origin main
