name: Run Python Scripts from Private Repo ( G )

on:
  workflow_dispatch:
  schedule:
    - cron: '45 */2 * * *'

concurrency:
  group: golvar-main
  cancel-in-progress: true

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (veriler)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies from private repo
        run: |
          pip install -r private_py/requirements.txt

      - name: Run ana_domain.py
        run: python private_py/golvar/ana_domain.py

      - name: Run mac_verileri.py
        run: python private_py/golvar/mac_verileri.py

      - name: Run link_alma.py
        run: python private_py/golvar/link_alma.py

      - name: Run m3u_link.py
        run: python private_py/golvar/m3u_link.py

      - name: Run kod_alma.py
        run: python private_py/golvar/kod_alma.py

      - name: Run link_hazırlama.py
        run: python private_py/golvar/link_hazırlama.py

      - name: Run encode.py
        run: python private_py/golvar/encode.py

      - name: Run verileri_birlestir.py
        run: python private_py/golvar/verileri_birlestir.py

      - name: Run txt_to_m3u.py
        run: python private_py/golvar/txt_to_m3u.py

      # Tüm değişiklikleri sahneye al
      - name: Add all changes
        run: |
          git add -A

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update all output files via workflow G" || echo "No changes to commit"
          git push origin main

  merge-m3u-playlists:
    needs: run-python-scripts  # Bu iş, "run-python-scripts" işinden sonra çalışacak
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 5 seconds
        run: sleep 5  # 5 saniye bekleme

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Merge M3U Playlists
        run: |
          python private_py/birlestir.py  # Python scriptini çalıştırır

      - name: Delete all files except ana_link.txt
        run: |
          find g/ -type f ! -name "ana_link.txt" -delete

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git diff --cached --quiet || (git commit -m "Update playlist.m3u and clean up files" && git push)
