name: Push

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Python Scripts from Private Repo ( S )"]
    types:
      - completed

jobs:
  merge-m3u-playlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Merge M3U Playlists
        run: |
          python private_py/birlestir.py

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git diff --cached --quiet || (git commit -m "Update playlist.m3u and clean up files via GitHub Actions" && git push)

  sync-root-folder:
    runs-on: ubuntu-latest
    needs: merge-m3u-playlists

    steps:
      - name: Wait 30 seconds before starting the sync process
        run: |
          echo "Waiting for 30 seconds before starting..."
          sleep 30

      - name: Checkout Public Repository (sitem3u)
        uses: actions/checkout@v4
        with:
          repository: 'MDuymazz/sitem3u'
          token: ${{ secrets.GH_TOKEN }}
          ref: main

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Copy m3u files from root folder to m3u8 folder in Private Py Repo
        run: |
          mkdir -p private_py/m3u8  # m3u8 klasörü oluştur
          cp *.m3u private_py/m3u8/  # Ana dizindeki tüm .m3u dosyalarını m3u8 içine kopyala

      - name: Check if .m3u files are copied
        run: |
          echo "Files in m3u8 folder:"
          ls private_py/m3u8  # Kopyalanan dosyaların burada olduğunu kontrol et

      - name: Configure Git for Commit (Again)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push to Private Py Repo (Even if no changes)
        run: |
          cd private_py
          git add m3u8/*.m3u
          # Commit'i değişiklikler olsa da olmasa da her zaman yap
          git commit --amend --no-edit || git commit -m "Sync root m3u files into m3u8 folder [auto]"
          git push origin main --force  # Force push ile commit'i yap
          
      - name: Create sil.txt (Trigger file)
        run: |
          echo "This is a trigger file" > sil.txt  # sil.txt dosyasını oluştur

      - name: Commit and Push sil.txt
        run: |
          git add sil.txt
          git commit -m "Create sil.txt to trigger next step"
          git push origin main
