name: Sync Root M3U Files to Private Repo (into m3u8 folder)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Merge"]
    types:
      - completed

jobs:
  sync-root-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (sitem3u)
        uses: actions/checkout@v4
        with:
          repository: 'MDuymazz/sitem3u'
          token: ${{ secrets.GH_TOKEN }}
          ref: main

      - name: Wait 20 seconds before starting
        run: |
          echo "Waiting for 20 seconds before starting..."
          sleep 20  # 20 saniye bekle

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Copy m3u files from root folder to m3u8 folder in Private Py Repo
        run: |
          mkdir -p private_py/m3u8  # m3u8 klasörü oluştur
          cp *.m3u private_py/m3u8/  # Ana dizindeki tüm .m3u dosyalarını m3u8 içine kopyala

      - name: Commit and Push to Private Py Repo
        run: |
          cd private_py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add m3u8/*.m3u
          git commit -m "Sync root m3u files into m3u8 folder [auto]" || echo "No changes to commit"
          git push origin main

  cleanup-folder:
    runs-on: ubuntu-latest
    needs: sync-root-folder

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Wait 30 seconds before cleaning
        run: |
          echo "Waiting for 30 seconds before cleaning..."
          sleep 30

      - name: Clean up unnecessary files and folders
        run: |
          # Ana dizinde playlist.m3u dosyasını sil
          if [ -f playlist.m3u ]; then
            rm playlist.m3u
          fi

          # V klasörü
          find v/ -type f ! -name 'data.html' -delete

          # D klasörü
          find d/ -type f ! -name 'livejson.py' ! -name 'logo.txt' ! -name 'schedule.json' -delete

          # G klasörü
          find g/ -type f ! -name 'ana_link.txt' ! -name 'logo.txt' -delete

          # S klasörü
          find s/ -type f ! -name 'ana_link.txt' ! -name 'logo.txt' -delete

      - name: Commit and Push Cleaned Files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Clean up folders and delete playlist.m3u [auto]" || echo "No changes to commit"
          git push
