name: Merge M3U and Push to Private Repo (V)

on:
  workflow_run:
    workflows: ["Run Python Scripts from Private Repo ( V )"]
    types:
      - completed
  workflow_dispatch:

jobs:
  merge-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_repo

      - name: Copy updated .m3u files to private repo
        run: |
          cp v/*.m3u private_repo/m3u/

      - name: Commit and Push to Private Repo
        run: |
          cd private_repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add m3u/*.m3u
          git commit -m "Update M3U files from public repo" || echo "No changes to commit"
          git push origin main

      - name: Clean v folder (keep data.html)
        run: |
          find v/ -type f ! -name "data.html" -delete
