name: Merge M3U Playlists and Push to Private Repo (V)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Python Scripts from Private Repo ( V )"]
    types:
      - completed

jobs:
  merge-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Merge M3U Playlists
        run: |
          python private_py/birlestir.py

      - name: Move M3U Files to Temporary Directory
        run: |
          mkdir m3u
          cp v/new_m3u.m3u m3u/
          cp v/programlar.m3u m3u/
          cp v/vavoo.m3u m3u/

      - name: Push M3U Files to Private Repo
        run: |
          cd m3u
          git init
          git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update M3U files from public repo"
          git push --force origin main:m3u-files

