name: Merge M3U Playlists and Push ( V )

on:
  workflow_run:
    workflows: ["Run Python Scripts from Private Repo ( V )"]  # İlk workflow'un adı
    types:
      - completed

  workflow_dispatch:

jobs:
  merge-m3u-playlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install requests 

      - name: Merge M3U Playlists
        run: |
          python private_py/birlestir.py  # Python scriptini çalıştırır

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Copy .m3u files to the 'm3u' directory
        run: |
          # m3u klasörüne dosyaları kopyalıyoruz
          mkdir -p m3u  # Eğer 'm3u' klasörü yoksa oluşturuyoruz
          cp new_m3u.m3u m3u/
          cp programlar.m3u m3u/
          cp vavoo.m3u m3u/

      - name: Add and Commit M3U Files
        run: |
          # Dosyaları git'e ekliyoruz
          git add m3u/new_m3u.m3u m3u/programlar.m3u m3u/vavoo.m3u
          
          # Değişiklikleri commit ediyoruz
          git diff --cached --quiet || (git commit -m "Update m3u playlists in m3u folder" && git push)

      - name: Push Changes to Private Repo
        run: |
          # Değişiklikleri gizli repoya push ediyoruz
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/sitem3u.git main
