name: Run Python Scripts from Private Repo ( V )

on:
  schedule:
    - cron: '0 */1 * * *'  # Her saat başında çalışacak şekilde
  workflow_dispatch:  # Manuel tetikleme için

concurrency:
  group: golvar-v
  cancel-in-progress: true

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (veriler)
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies from private repo
        run: |
          pip install -r private_py/requirements.txt

      - name: Run data_html.py
        run: python private_py/vavoo/data_html.py

      - name: Run kanallar.py
        run: python private_py/vavoo/kanallar.py

      - name: Run generate_m3u.py
        run: python private_py/vavoo/generate_m3u.py

      - name: Run dizi_gunluk.py
        run: python private_py/vavoo/dizi_gunluk.py

      - name: Run diziler_m3u.py
        run: python private_py/vavoo/diziler_m3u.py

      - name: Run sporekrani.py
        run: python private_py/vavoo/sporekrani.py

      - name: Run spor_ekrani_m3u.py
        run: python private_py/vavoo/spor_ekrani_m3u.py

      # Tüm değişiklikleri sahneye al
      - name: Add all changes
        run: |
          git add -A  # Bu komut, tüm değişiklikleri sahneye alır

      - name: Commit and Push Changes
        run: |
          # Git bilgilerini yapılandır
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Değişiklikleri commit et
          git commit -m "Update all output files and playlist.m3u via workflow V" || echo "No changes to commit"

          # Değişiklikleri push et
          git push origin main
