name: Merge M3U Playlists and Push ( V )

on:
  workflow_run:
    workflows: ["Run Python Scripts from Private Repo ( V )"]
    types:
      - completed

  workflow_dispatch:

jobs:
  merge-and-sync:
    runs-on: ubuntu-latest

    steps:
      # === İlk olarak: v klasöründeki .m3u dosyalarını Py reposuna kopyala ve push et ===

      - name: Checkout General Repo (sitem3u)
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout Private Repo (Py) using GH_TOKEN
        uses: actions/checkout@v3
        with:
          repository: MDuymazz/Py
          token: ${{ secrets.GH_TOKEN }}
          path: py

      - name: Copy M3U Files from General Repo to Py Repo
        run: |
          mkdir -p py/m3u8
          cp -f v/*.m3u py/m3u8/

      - name: Commit & Push to Py Repo
        working-directory: py
        run: |
          git add .
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Sync M3U files from sitem3u"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git HEAD:main

      # === Ardından: Python scriptini çalıştır ve güncellenen playlist.m3u dosyasını ana repoya push et ===

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Merge M3U Playlists
        run: |
          python private_py/birlestir.py

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git diff --cached --quiet || (git commit -m "Update playlist.m3u and clean up files via GitHub Actions" && git push)
