name: Run Python Scripts from Private Repo ( V )

on:
  workflow_dispatch:          # Manuel tetikleme için
  schedule:
    - cron: '30 21 * * *'     # Her gün 21:30'da çalışır

concurrency:
  group: golvar-v
  cancel-in-progress: true

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (veriler)
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies from private repo
        run: |
          pip install -r private_py/requirements.txt

      - name: Run data_html.py
        run: python private_py/vavoo/data_html.py

      - name: Run kanallar.py
        run: python private_py/vavoo/kanallar.py

      - name: Run generate_m3u.py
        run: python private_py/vavoo/generate_m3u.py

      - name: Run dizi_gunluk.py
        run: python private_py/vavoo/dizi_gunluk.py

      - name: Run diziler_m3u.py
        run: python private_py/vavoo/diziler_m3u.py

      - name: Run sporekrani.py
        run: python private_py/vavoo/sporekrani.py

      - name: Run spor_ekrani_m3u.py
        run: python private_py/vavoo/spor_ekrani_m3u.py

      - name: Run birlestir.py
        run: python private_py/birlestir.py

      # Playlist dosyasını sil ve yeniden oluştur
      - name: Delete and Recreate playlist.m3u
        run: |
          git rm playlist.m3u || true
          python private_py/birlestir.py
          # Tüm değişiklikleri sahneye al
          git add -A  # <-- Bu komutla değişiklikleri sahneye alıyoruz

      - name: Commit and Push Changes
        run: |
          # Git bilgilerini yapılandır
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Değişiklikleri commit et
          git commit -m "Update output files via workflow V" || echo "No changes to commit"  # Eğer değişiklik yoksa commit işlemi yapılmaz

          # Değişiklikleri push et
          git push origin main
