name: Run Python Scripts from Private Repo ( V )

on:
  workflow_dispatch:          # Manuel tetikleme için
  schedule:
    - cron: '30 21 * * *'     # Her gün 21:30'da çalışır

concurrency:
  group: golvar-v
  cancel-in-progress: true

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository (veriler)
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies from private repo
        run: |
          pip install -r private_py/requirements.txt

      - name: Run data_html.py
        run: python private_py/vavoo/data_html.py

      - name: Run kanallar.py
        run: python private_py/vavoo/kanallar.py

      - name: Run generate_m3u.py
        run: python private_py/vavoo/generate_m3u.py

      - name: Run dizi_gunluk.py
        run: python private_py/vavoo/dizi_gunluk.py

      - name: Run diziler_m3u.py
        run: python private_py/vavoo/diziler_m3u.py

      - name: Run sporekrani.py
        run: python private_py/vavoo/sporekrani.py

      - name: Run spor_ekrani_m3u.py
        run: python private_py/vavoo/spor_ekrani_m3u.py

      # Tüm değişiklikleri sahneye al
      - name: Add all changes
        run: |
          git add -A  # Bu komut, tüm değişiklikleri sahneye alır

      - name: Commit changes if any
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Update output files via workflow V" || echo "No changes to commit"

      # Uzak depodaki değişiklikleri çek ve rebase yap
      - name: Pull latest changes from remote before pushing
        run: |
          git fetch origin main
          git rebase origin/main  # Rebase yaparak uzak depo ile uyumlu hale gel

      - name: Commit and Push Changes
        run: |
          git push origin main

  merge-m3u-playlists:
    needs: run-python-scripts  # Bu iş, "run-python-scripts" işinden sonra çalışacak
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 20 seconds
        run: sleep 20  # 20 saniye bekleme

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install requests 

      - name: Merge M3U Playlists
        run: |
          python private_py/birlestir.py  # Python scriptini çalıştırır

      - name: Delete all files except data.html
        run: |
          find v/ -type f ! -name "data.html" -delete

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull latest changes from remote before pushing
        run: |
          git fetch origin main
          git rebase origin/main  # Rebase yaparak uzak depo ile uyumlu hale gel

      - name: Commit and Push Changes
        run: |
          git add .
          git diff --cached --quiet || (git commit -m "Update playlist.m3u via GitHub Actions" && git push)
