name: Merge M3U Playlists and Push ( V )

on:
  workflow_run:
    workflows: ["Run Python Scripts from Private Repo ( V )"]  # İlk workflow'un adı
    types:
      - completed

jobs:
  merge-m3u-playlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone Private Repository (Py)
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/MDuymazz/Py.git private_py

      - name: Install Python dependencies
        run: |
          pip install requests 

      - name: Merge M3U Playlists
        run: |
          python private_py/birlestir.py  # Python scriptini çalıştırır

      - name: Delete all files except data.html
        run: |
          find v/ -type f ! -name "data.html" -delete

      - name: Configure Git for Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          # Stage the playlist.m3u file for commit
          git add playlist.m3u

          # Check if there are any changes to commit
          git diff --cached --quiet || (git commit -m "Update playlist.m3u via GitHub Actions" && git push)
