name: Workflow Geçmişini Temizle

on:
  workflow_dispatch:  # Manuel olarak başlatılabilir

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarını al
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: requests kütüphanesini yükle
        run: pip install requests

      - name: Workflow geçmişini sil
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: python delete_runs.py
